[theme]
# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "light"

# Primary accent color for interactive elements.
primaryColor = "#F58220"

# Background color for the main content area.
# backgroundColor = "#cdcecb"
